blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('tag/<slug:tag_slug>/',views.index, name='post_list_by_tag'),
    path('<int:id>/', views.post_detail, name='post_detail'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blogapp/', include("blogapp.urls")),
    path('admin/', admin.site.urls),
]

blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                                    .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft',
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    tags = TaggableManager()
    author = models.ForeignKey(User,
                                                on_delete=models.CASCADE,
                                                related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    #Se establece automaticamente la fecha en la que fue creado
    created = models.DateTimeField(auto_now_add=True)
    #Se establece automaticamente la fecha cuando se modifica
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                                                        choices=Status.choices,
                                                        default=Status.DRAFT)

    objects = models.Manager()
    published = PublishedManager()

    #Define que se presenten en orden descendiente los post
    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish']),]

    #Presentacion del objeto
    def __str__(self):
        return self.title

    
class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blogapp/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blogapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from .forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
# Create your views here.

'''Funcion que muestra el  Index'''
#Post list
def index(request,tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                                "./blogapp/base.html",
                                 {'posts': posts,
                                 'tag': tag})



def post_detail(request,id):
    post = get_object_or_404(Post,
                             id=id,
                             status = Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    
    #Lista de post similares
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags','-publish')[:4]
    
    return render(request,
                  './blogapp/detail.html',
                  {'post': post,
                   'comments': comments,
                   'similar_posts': similar_posts})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, \
                                   status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(request, 'blogapp/comment.html',
                           {'post': post,
                            'form': form,
                            'comment': comment})

blogapp/templates/blogapp/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  {% block cssstyle %}
  <!-- Materialize CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- CSS -->
  <link href="{% static '/blogapp/css/style.css'%} " type="text/css" rel="stylesheet" media="screen,projection" />
  {% endblock cssstyle %}
</head>

<body>

  {% block navbar %}
  <!-- Barra de navegacion -->
  <!-- <nav>
    <div class="nav-wrapper grey darken-3">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul>
    </div>
  </nav> -->

  <nav class="nav-extended">
    <div class="nav-wrapper">
      <a href="/blogapp" class="brand-logo" id="logo"><i class="material-icons">create</i> Blog</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">Home</a></li>
        <li><a href="collapsible.html">Ingresar</a></li>
      </ul>
    </div>
    <div class="nav-header center">
      <h1>I MAKE THINGS</h1>
      <div class="tagline">Portfolio</div>
    </div>
    <div class="nav-content">
      <ul class="tabs tabs-transparent" id="tab_down">
        <li class="tab"><a href="#">All</a></li>
        <li class="tab"><a class="active" href="#test2">Populares</a></li>
        <li class="tab "><a href="#">Recientes</a></li>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">JavaScript</a></li>
  </ul>

  {% endblock navbar %}


  {% block parallax %}
  <!-- Banner Parallax-->
  <!-- <div class="parallax-container">
    <div class="parallax">
      <img src="{% static '/blogapp/img/banner.jpg' %}" class="responsive-img">
    </div>
  </div> -->
  {% endblock parallax %}


  {% block content %}
  <!-- Post -->
  <div class="container section">
    <h1>Post</h1>
    <p>Hay un total de {% total_posts %} post</p>
    <h3>Latest posts</h3>
      {% show_latest_posts 3 %}

    <h3>Most commented posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
      {% for post in most_commented_posts %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    </ul>
      {% endfor %}
    <div class="row">
      <!-- Inicio del ciclo for para mostar las categorias -->
      <div class="divider"></div>
      <div class="section">
        {% if tag %}
        <h2> Publicacion con tag:"{{ tag.name }}" </h2>
        {% endif %}
        {% for post in posts %}
        <div class="col s12 m6 l4">
          <div class="card medium hoverable">
            <div class="card-image">
              <img class="responsive-img" src="{% static '/blogapp/img/letter.jpg' %}" alt="">
            </div>
            <div class=" card-content">
              <span class=" card-title">{{post.title}}</span>
              <p>{{ post.body|truncatewords:50|linebreaks }}</p>
            </div>
            <div class="card-action">
              <a class="waves-effect waves-light btn" href="{{ post.id }}/">Entrar</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endblock content %}

  {% include 'blogapp/pagination.html' with page=posts %}


  {% block js %}
  <script src=" https://code.jquery.com/jquery-2.1.1.min.js"> </script>
  <script src="{% static '/blogapp/js/init.js' %}"></script>
  <script src=" {% static '/blogapp/js/materialize.js' %} "></script>
  {% endblock js %}



</body>

</html>

blogapp/templates/blogapp/detail.html
{% extends 'blogapp/base.html' %}


{% block content %}
<div class="contariner">
    <div class="row">
        <div class="col l12">
            <h2 class="center-align"> {{ post.title }}</h2>
            <p>Tags:
                {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}</p>
            <p class="center-align">{{ post.body }}</p>
        </div>
    </div>
</div>
{% with comments.count as total_comments %}
<p>
    {{ total_comments}} comment{{total_comments|pluralize }}
</p>
{% endwith %}



{% for comment in comments %}
<ul class="collapsible">
    <li>
        <div class="collapsible-header"><i class="material-icons">filter_drama</i> Comment {{ forloop.counter }} by
            {{comment.name}} {{ comment.created }}</div>
        <div class="collapsible-body"><span>{{comment.body}}.</span></div>
    </li>
    {% empty %}
    <p>No hay comentarios</p>
</ul>
{% endfor %}

<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
<a href="{{ post.id }}/">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}

{% endblock content %}

blogapp/templates/blogapp/email.html
{% extends 'blogapp/base.html' %}

{% block title %}
<h3>Comparte el post</h3>
{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Email enviado correctamente</h1>
        <p>
            {{ post.title }} fue enviado correctamente a {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h3>Share {{post.title}} by email</h3>
        <form action="post" novalidate>
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

blogapp/templates/blogapp/lastest_post.html
<ul>
    {% for post in latest_posts %}
    <li>
    <a href="{{ post.id }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blogapp/templates/blogapp/pagination.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

<span>
  {% if page.has_previous %}
  <a href="?page={{ page.previous_page_number }}">Previous</a>
  {% endif %}
  <span>
    Page {{ page.number }} of {{page.paginator.num_pages }}
  </span>

  {% if page.has_next %}
  <a href=" ?page={{ page.next_page_number }}">Next</a>
  {% endif %}
</span>